# Generated by Django 4.2.5 on 2024-01-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shadow", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("phone_no", models.IntegerField()),
                ("subject", models.CharField(max_length=250)),
                ("content", models.TextField()),
                ("update", models.DateTimeField(auto_now=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-timestamp", "-update"],
            },
        ),
        migrations.AlterField(
            model_name="shadow_user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
    ]
